# Module 3: Working with Vectors, Matrices, and Arrays in Python
This notebook covers the use of NumPy for operations involving vectors, matrices, arrays, and reshaping techniques. It includes explanations, code examples, and best practices for data scientists and AI/ML engineers.

## 3.1 Working with Vectors
A **vector** in Python using NumPy is a one-dimensional array. Let's begin by creating and accessing its elements.

In [1]:
import numpy as np

# Create a vector
vector = np.array([2, 4, 6, 8, 10])
print("Vector:", vector)

Vector: [ 2  4  6  8 10]


In [4]:
# Accessing element '6' in two ways
print("Method 1:", vector[2])
print("Method 2:", vector[-2])

Method 1: 6
Method 2: 8


## 3.2 Working with Matrices
A **matrix** is represented as a 2D array. Let's create one and access an element within it.

In [9]:
# Create a 3x3 matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:\n", matrix)
print("Element of our matrix at [2][2]:", matrix[2][2])

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element of our matrix at [2][2]: 9


## 3.3 Matrix Descriptions and Operations
Understanding shape, size, and dimension of a matrix.

In [11]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Shape:", matrix.shape)
print("Size:", matrix.size)
print("Dimensions:", matrix.ndim)

Shape: (3, 3)
Size: 9
Dimensions: 2


In [14]:
# Arithmetic operations
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 3]])
print(a)
print(b)
print("Dot Product:\n", np.dot(a, b))
print("Addition:\n", np.add(a, b))
print("Subtraction:\n", np.subtract(a, b))

[[1 2]
 [3 4]]
[[2 0]
 [1 3]]
Dot Product:
 [[ 4  6]
 [10 12]]
Addition:
 [[3 2]
 [4 7]]
Subtraction:
 [[-1  2]
 [ 2  1]]


### Challenge: Manual Matrix Multiplication
$C = A \times B = C_{ij} = \sum_{k=1}^{n} a_{ik} \cdot b_{kj}$



In [24]:
def manual_matrix_multiply(A, B):
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result

A = [[1, 2], [3, 4]]
B = [[2, 0], [1, 3]]
print("Manual Multiplication Result:\n", manual_matrix_multiply(A, B))

c = np.matmul(A,B)
print("Automatic\n" , c)


Manual Multiplication Result:
 [[4, 6], [10, 12]]
Automatic
 [[ 4  6]
 [10 12]]


## 3.4 Array Manipulations and Lambda Functions

In [25]:
# Lambda function examples
add_15 = lambda a: a + 15
multiply = lambda a, b, c: a * b * c
print("Add 15:", add_15(10))
print("Multiply:", multiply(2, 3, 4))

Add 15: 25
Multiply: 24


In [32]:
# Vectorizing a function
def square(x): return x ** 2
vec_func = np.vectorize(square)
my_vec = np.array([1, 2, 3, 4])
print("Vectorized Result:", vec_func(my_vec))

Vectorized Result: [ 1  4  9 16]


### Statistical Functions and Random Value Generation

In [35]:
# Random array and basic stats
arr = np.random.randint(10, 100, size=(4, 4))
print("Array:\n", arr)
print("Row-wise Max:", np.max(arr, axis=1))
print("Column-wise Mean:", np.mean(arr, axis=0))

Array:
 [[23 89 53 10]
 [83 87 33 79]
 [10 64 79 45]
 [50 62 36 31]]
Row-wise Max: [89 87 79 62]
Column-wise Mean: [41.5  75.5  50.25 41.25]


In [36]:
# Different distributions
print("Normal:", np.random.normal(0, 1, 5))
print("Logistic:", np.random.logistic(0, 1, 5))
print("Uniform:", np.random.uniform(0, 10, 5))

Normal: [-1.85929017  0.29758254 -0.34706121 -0.42010367 -1.1912853 ]
Logistic: [-1.85817264  0.47253337 -0.14115011 -4.58834503 -2.78508044]
Uniform: [4.58172544 6.97256107 2.27937496 4.10475176 5.95901178]


## 3.5 Reshaping Arrays

In [38]:
# Reshape with -1
arr = np.arange(12)
reshaped = arr.reshape(3, 4)
print("Original:", arr)
print("Reshaped:\n", reshaped)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
